server:
  port: ${PORT:8081}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:auth-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:12345}
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql
    maxActive: 3
  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show_sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}